name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
sort-direction: ascending

categories:
  - title: "📚 Documentation"
    labels:
      - "documentation"
  - title: "💥 Breaking Changes"
    labels:
      - "breaking-change"
  - title: "✨ New Features"
    labels:
      - "new-feature"
  - title: "🐛 Bug Fixes"
    labels:
      - "bugfix"
  - title: "🎨 Style"
    labels:
      - "style"
  - title: "📦 Refactor"
    labels:
      - "refactor"
  - title: "🚀 Performance"
    labels:
      - "performance"
  - title: "🧪 Test"
    labels:
      - "test"
  - title: "🛠️ Build"
    labels:
      - "build"
  - title: "⚙️ CI"
    labels:
      - "ci"
  - title: "♻️ Chore"
    labels:
      - "chore"
  - title: "🗑️ Revert"
    labels:
      - "revert"
  - title: "⬆️ Dependency Updates"
    labels:
      - "dependencies"
    collapse-after: 3

template: |
  ## Changes
  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

  ## 🧡 Contributors
  $CONTRIBUTORS

version-resolver:
  major:
    labels:
      - "breaking-change"
  minor:
    labels:
      - "new-feature"
  patch:
    labels:
      - "bugfix"
      - "chore"
      - "dependencies"
  default: patch
