[mypy]
python_version = 3.14
show_error_codes = True
incremental = True
ignore_missing_imports = True
explicit_package_bases = True
namespace_packages = True
mypy_path = custom_components
exclude = custom_components/.*
