name: Bug Report
description: Create a report to help us improve the HYXi integration
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 
        **Please ensure you have read the Troubleshooting section in the README and have your Debug Logs ready.**
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: The integration loads, but my Solar Power sensor stays at 0W...
    validations:
      required: true
  - type: input
    id: device_type
    attributes:
      label: HYXi Device Type / Model
      description: What specific hardware are you having trouble with? (e.g., Hybrid Inverter, Meter, Collector Stick)
      placeholder: e.g., HYBRID_INVERTER
    validations:
      required: true
  - type: input
    id: ha_version
    attributes:
      label: Home Assistant Version
      description: What version of Home Assistant Core are you running?
      placeholder: e.g., 2024.2.1
    validations:
      required: true
  - type: input
    id: integration_version
    attributes:
      label: Integration Version
      description: Which version of this integration are you using?
      placeholder: e.g., v1.0.9
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Debug Logs
      description: |
        Please paste your Home Assistant debug logs here. 
        (Go to Settings > Devices & Services > HYXi Cloud > Enable debug logging. Wait 5 minutes, then Disable and download).
      render: shell
    validations:
      required: true