name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from manifest.json
        id: get_version
        run: |
          VERSION=$(jq -r '.version' custom_components/hyxi_cloud/manifest.json)
          echo "Extracted version: $VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update Release Draft
        uses: release-drafter/release-drafter@v6.2.0
        with:
          version: ${{ steps.get_version.outputs.version }}
          commitish: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
